### ISSUE TITLE
Certain extensions have the wrong download URL for the stated version

### ISSUE THREAD

**Issue by xlash123** [NetLogo/NetLogo-Libraries#13]
Certain extensions, such as GIS, CSV, and VID, have discrepancies with the stated version and the version that is downloaded the from downloadURL. This causes annoying popup boxes to appear every time NetLogo is started

**Comment by LaCuneta** [comment]
Noah, thanks for the report, sorry you ran into the issues with the extension manager.  

I saw the incorrect URLs for the bundled extensions and got those updated, so they should be correct now.  

I am curious how you noticed the difference, so I can better understand your use case.  When I tried using the extensions with 6.1 I didn't have any issues, and the extension manager wouldn't let me update them with the wrong URLs since the versions matched.  Did you manually download extensions from their URLs for some reason?  Or did you see different behavior than what I saw with the extensions manager?

Thanks again!

**Comment by xlash123** [comment]
I was running the model as a Java program using the API. When running in GUI mode, it would prompt me to download the extensions, as I'm guessing it can't see the bundled extensions when run like this.

**Comment by LaCuneta** [comment]
Ah, gotcha, that makes more sense.

**Comment by LaCuneta** [comment]
@xlash123 It just occurred to me that you may need to delete your user-specific extensions folder to get the correct new versions downloaded.  Check out [item #3 in this doc](https://ccl.northwestern.edu/netlogo/docs/extensions.html#where-extensions-are-located) for the details on where it is.  It's totally safe to delete as long as NetLogo isn't running, the manager will just re-download what it needs on the next run.

**Comment by xlash123** [comment]
I already have and all it working. Thank you.
