### ISSUE TITLE
Include bundled extensions

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo-Libraries#3]

**Comment by Idloj** [comment]
@TheBizzle, two points on this:
 - Why do we want this in the first place?
 - It's not clear how this can be done because the bundled extensions are found in the NetLogo installation directory while the Libraries Dialog manages the extensions in the per-user App Data directory

**Comment by TheBizzle** [comment]
We want this because (a) you can then open the Extension Manager and see the full list of extensions that you have installed, and (b) if they are easily downloadable with the Extension Manager, it will be easier to make the case that we don't need to bundle _any_ extensions anymore.

I'm not understanding the second problem you mention.  If NetLogo comes with Array version A, and we host Array version B here, and then download it through the Extension Manager, doesn't NetLogo now use Array version B when I say `extensions [array]`?

**Comment by Idloj** [comment]
After some more thought, I think this is possible with the following plan:
- Bundled extensions cannot be uninstalled
- Bundled extensions' version will initially (after installing NetLogo) be the same as the NetLogo version that bundles them. The version obviously will be changed when updating a bundled extension to reflect the updated version.

**Comment by TheBizzle** [comment]
Sure, that's fine.

**Comment by Idloj** [comment]
The final plan is for NetLogo to come with an initial version of `installed-libraries.conf` which will be copied to the App Data folder.
